# Generated by Django 3.2 on 2022-06-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
